// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhJrA5n2lPjhI3Jti7SCM8s7s5JsW_9kw',
    appId: '1:188442451118:web:ad7b638edc0eba4d9a613f',
    messagingSenderId: '188442451118',
    projectId: 'prakflutterfirebase-20894',
    authDomain: 'prakflutterfirebase-20894.firebaseapp.com',
    storageBucket: 'prakflutterfirebase-20894.appspot.com',
    measurementId: 'G-ZBZ5QZ8XQH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHz4VZbqmN8abSFsL45oAGbcegDKo3AmI',
    appId: '1:188442451118:android:72be13bf2fa9a9789a613f',
    messagingSenderId: '188442451118',
    projectId: 'prakflutterfirebase-20894',
    storageBucket: 'prakflutterfirebase-20894.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-HtxpbxhpVSd-1XyFcR82m-7LwpYQ9Pk',
    appId: '1:188442451118:ios:a04ef8706053288b9a613f',
    messagingSenderId: '188442451118',
    projectId: 'prakflutterfirebase-20894',
    storageBucket: 'prakflutterfirebase-20894.appspot.com',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-HtxpbxhpVSd-1XyFcR82m-7LwpYQ9Pk',
    appId: '1:188442451118:ios:a04ef8706053288b9a613f',
    messagingSenderId: '188442451118',
    projectId: 'prakflutterfirebase-20894',
    storageBucket: 'prakflutterfirebase-20894.appspot.com',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhJrA5n2lPjhI3Jti7SCM8s7s5JsW_9kw',
    appId: '1:188442451118:web:22330e5ab69aa68d9a613f',
    messagingSenderId: '188442451118',
    projectId: 'prakflutterfirebase-20894',
    authDomain: 'prakflutterfirebase-20894.firebaseapp.com',
    storageBucket: 'prakflutterfirebase-20894.appspot.com',
    measurementId: 'G-EZQ83YYY9K',
  );

}